version: '2'

services:
  postgres:
    image: 'postgres:9.6-alpine'
    volumes:
      - 'postgres:/var/lib/postgresql/data'

  app:
    depends_on:
      - 'postgres'
    build: .
    ports:
      - '9292:9292'
    volumes:
      - '.:/onebot'
    environment:
      - LANG=C.UTF-8

volumes:
  postgres:
